### ISSUE TITLE
Problems with Gulp

### ISSUE THREAD

**Issue by dwwhall** [pkerpedjiev/fornac#34]
The development phase is not working on my device.  Below is the error message for the gulp serve command.

$ gulp serve
Requiring external module @babel/register
Error: Plugin/Preset files are not allowed to export objects, only functions.  

I have tried to upgrade and downgrade gulp, nvm, and bower, and I uninstalled and reinstalled gulp, nvm, and bower.  

Additional Information:
macOS Mojave Version 10.14.6

**Comment by pkerpedjiev** [comment]
Hey, can you try installing `nvm`, switching to Node 10 and trying again?

The following worked for me:

1. Install nvm:

```
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
```

2. Use Node 10:

```
nvm install 10 && nvm use 10
```

3. Start

```
gulp serve
```

**Comment by dwwhall** [comment]
> Hey, can you try installing `nvm`, switching to Node 10 and trying again?
> 
> The following worked for me:
> 
> 1. Install nvm:
> 
> ```
> curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash
> ```
> 
> 1. Use Node 10:
> 
> ```
> nvm install 10 && nvm use 10
> ```
> 
> 1. Start
> 
> ```
> gulp serve
> ```

**Comment by dwwhall** [comment]
Thank you, Peter Kerpedjiev.  The solution worked on my device!
