### ISSUE TITLE
Export in png and svg

### ISSUE THREAD

**Issue by jpsglouzon** [pkerpedjiev/fornac#6]
Hi,
How can we export the structures generate with fornac in png and svg?
Thanks.

**Comment by pkerpedjiev** [comment]
Hey,

You can't export to SVG or PNG natively, but you can use [SVG Crowbar](http://nytimes.github.io/svg-crowbar/) to extract its contents as an SVG. If you want native SVG or PNG export, I recommend using [forna](http://nibiru.tbi.univie.ac.at/forna/).

**Comment by jpsglouzon** [comment]
I'll try forna.
Thanks
